# Generated by Django 4.1.3 on 2022-11-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clpperufmodel",
            unique_together={("value", "date")},
        ),
    ]
